name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the build from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install flit

      - name: Install twine
        run: pip install twine

      - name: Build package
        run: flit build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          echo "Uploading package to PyPI..."
          python -m twine upload --repository pypi dist/*
